config/routes.rb
TigrCms::Application.routes.draw do
  resources :sessions
  match 'login', to: 'sessions#new', as: :login
  match 'logout', to: 'sessions#destroy', as: :logout

  mount Ckeditor::Engine => '/ckeditor'

  root to: 'pages#main'

  resources :pages do
    post :update_content
    collection { post :sort }
  end

  match 'main', to: 'pages#main', as: :main

  match '*permalink', to: 'pages#show'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset
  include Ckeditor::Orm::Mongoid::AssetBase
  include Mongoid::Paperclip
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_mongoid_attached_file :data,
                            :url => "/ckeditor_assets/attachments/:id/:filename",
                            :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_mongoid_attached_file :data,
                            :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                            :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                            :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/page.rb
class Page
  include Mongoid::Document
  include Mongoid::Versioning

  include Mongoid::Orderable
  orderable

  include Mongoid::Ancestry
  has_ancestry

  default_scope asc(:position)
  scope :all_without_main, asc(:position).ne(permalink: 'main')

  field :permalink
  field :title
  field :content

  validates_uniqueness_of :permalink
  validates_format_of :permalink, with: /\A\w[\w|\-]+\w\z/

  def main?
    permalink == 'main'
  end

  def path
    parent_path + permalink
  end

  def parent_path
    ancestry.nil? ? '/' : '/' + ancestors.pluck(:permalink).join('/') + '/'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :get_menu_pages

  protected

  def get_menu_pages
    @menu_pages = Page.all_without_main.roots
  end

  def admin?
    session[:login] == 'admin' && session[:password] == 'secret'
  end
  helper_method :admin?

  def authorize
    if admin?
      true
    else
      flash[:alert] = 'Unauthorized'
      redirect_to root_path
      false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authorize, except: [:main, :show]
  def main
    @page = Page.find_by(permalink: 'main')
  end

  def show
    @page = Page.find_by(permalink: params[:permalink].split('/').last)
    @version = @page.versions.find{|p| p.version == params[:version]} if params[:version]
    @pages = @page.root.children

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  def new
    @page = Page.new
    if params[:from_page]
      parent_page = Page.where(permalink: params[:from_page]).first
      @page.parent_id = parent_page.id
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to "/#{@page.permalink}", notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to "/#{@page.permalink}", notice: 'Page was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def update_content
    @page = Page.find(params[:page_id])
    respond_to do |format|
      if @page.update_attributes(content: params[:content], permalink: params[:permalink], title: params[:title], parent_id: params[:parent_id])
        format.js
      end
    end
  end

  def sort
    pages = params[:page]
    pp pages
    positions = pages.map {|id| Page.find(id).position }.sort

    pp positions
    pages.each_with_index do |id, index|
      puts "#{id} - #{index} - #{positions[index]}"
      Page.find(id).update_attribute(:position, positions[index])
    end
    render nothing: true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:login] = params[:session][:login]
    session[:password] = params[:session][:password]
    if authorize
      flash[:notice] = 'Successfully logged in'
      redirect_to root_path
    else

    end
  end

  def destroy
    reset_session
    flash[:notice] = 'Successfully logged out'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tigr CMS
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    - if alert.present?
      #alert.alert.alert-error
        %a.close{"data-dismiss" => "alert", href: "#"} ×
        = alert
    - if notice.present?
      #alert.alert.alert-success
        %a.close{"data-dismiss" => "alert", href: "#"} ×
        = notice
    .container
      = link_to 'Main', root_path
      - if admin?
        Admin
        = link_to 'Logout', logout_path

      = content_tag :ul, class: 'nav nav-tabs', id: ('menu' if admin?), data: {update_url: sort_pages_url} do
        - @menu_pages.each do |page|
          = content_tag_for :li, page, class: ("active" if @page.try(:root) == page) do
            = link_to page.title, "/#{page.permalink}"
        - if admin?
          %li{class: ('active' if params[:action] == 'new')}= link_to 'New page', new_page_path
      .row
        .span4
          - if @pages.present?
            .well.sidebar-nav
              = render 'pages/submenu_pages', pages: @page.root.children

        .span8
          = yield

      %hr
      - if admin?
        = link_to 'New page', new_page_path(from_page: @page.permalink)
      - unless admin?
        = link_to 'Admin login', login_path

app/views/pages/_form.html.haml
= semantic_form_for @page do |f|
  = f.inputs do
    - unless @page.main?
      = f.input :permalink, wrap_html: "#{@page.parent_path}/"
      = f.input :parent_id, as: :select, collection: (Page.all_without_main - [@page])
    = f.input :title
    = f.input :content, as: :ckeditor
  = f.actions

app/views/pages/_page.html.haml
- page = @version.present? ? @version : @page
- if admin?
  - unless @page.path == '/main'
    #page_path
      %p= @page.path
      =form_tag page_update_content_url(page), style: "display:none" do
        %span#prefix #{@page.parent_path}
        = text_field_tag :permalink, page.permalink
        %select{name: 'parent_id', id: "parent_id"}
          %option
          - (Page.all_without_main - [@page]).each do |p|
            %option{value: p.id, 'data-path' => p.permalink, selected: (p.id == page.parent_id ? "selected" : nil)} 
              = p.title
        = link_to "Принять", "#", class: 'btn btn-mini btn-success', id: 'hide_link'
  %h1#page_title{contenteditable: 'true'}
    = page.title
- else
  %h1= page.title

- if @page.version > 1
  Versions:
  - @page.versions.sort_by(&:version).each do |p|
    = link_to_unless_current p.version, "#{@page.path}?version=#{p.version}"
  = link_to_if params[:version], 'current', @page.path

- if admin?
  #editable{contenteditable: 'true'}
    = raw page.content

  = link_to 'Edit', edit_page_path(@page)
  - unless @page.main?
    = link_to 'Destroy', @page, method: :delete, data: { confirm: 'Are you sure?' }
  .pull-right
    = link_to 'Save', '#', id: 'save-editable', class: 'btn btn-primary', style: 'display:none', data: {loading_text: 'Save...'}
- else
  = raw @page.content

app/views/pages/_submenu_pages.html.haml
= content_tag :ul, class: 'nav nav-list', id: ('submenu' if admin?), data: {update_url: sort_pages_url} do
  - pages.each do |page|
    = content_tag_for :li, page do
      = link_to_unless_current page.title, page.path
      = render 'submenu_pages', pages: page.children if page.children.present?

app/views/pages/edit.html.haml
= render 'form'

app/views/pages/main.html.haml
= render 'page'

app/views/pages/new.html.haml
= render 'form'

app/views/pages/show.html.haml
= render 'page'

app/views/pages/update.js.erb
$('.container').prepend("<div class='alert alert-success'>Saved</div>")

app/views/pages/update_content.js.erb
$("#save-editable").addClass('btn-success').html("<i class='icon-ok icon-white'></i> &nbsp;Success");
$("form").hide();
$("#page_title").show();
window.location.href = "<%= @page.path %>"